### ISSUE TITLE
Respect Cache Header

### ISSUE THREAD

**Issue by hottehead** [jpodwys/superagent-cache-plugin#11]
I scanned the docs and the code and I saw that the cache plugin does not respect cache header Expires and Cache-Control which may be sent from the upstream. 

Is this correct? Is this on purpose? 
If not I would implement this and create a PR.

**Comment by jpodwys** [comment]
You're correct, this repo does not respect cache headers. I'm open to supporting this (thank you for being willing to open a PR).

There is already [a fork of this repo](https://github.com/finanzcheck/superagent-cache-plugin) that adds cache header support. They submitted [a PR](https://github.com/jpodwys/superagent-cache-plugin/pull/6) in early 2018. At the time, I was weary of adding third-party libraries directly to this repo, so I raised that concern.

I'm now willing to reconsider merging their changes into this repo. It looks like they're currently 21 commits ahead and 6 commits behind, so there may be some conflicts, but probably nothing big.

Please have a look at that fork and let me know if it would meet your needs.

**Comment by hottehead** [comment]
I checked the PR. This meets my needs. I think the solution is well done and should be merged. 

How about reopening the PR? The changes seem valid as is. And there are [no more required changes on master that are not on the feature branch](https://github.com/finanzcheck/superagent-cache-plugin/compare/feature/CORE-440-respect_response_cache_headers...finanzcheck:master).

Using https://github.com/kornelski/http-cache-semantics#readme package seems valid even though it's third party, considering the complexity of cache policies.

**Comment by jpodwys** [comment]
Thank you for your thoughts! I'll reopen the PR and reach out to the fork owners.
