### ISSUE TITLE
Cache Header Default Expiration

### ISSUE THREAD

**Issue by hottehead** [jpodwys/superagent-cache-plugin#12]
I have set a default expiration for all responses like this

```
const redisConfig = {
    redisData: {
        hostname: this.options.cacheHost,
        port: 6379,
    },
    type: 'stable-sdk',
};
this.redisCache = new RedisCache(redisConfig);
this.cache = superagentCache(this.redisCache, {
  expiration: 20
});
```

and then tried to set `Cache-Control: no-cache` on the request. This should result in the response not being cached. Instead the ttl is still 20 * 2 = 40 seconds. This is contrary to the docs. 

Sadly I couldnt find how this happens. The Cache-Control header should not be overwritten if it is already present with value "no-cache|no-store|max-age=0".

**Comment by jpodwys** [comment]
Just to confirm, have you pinned to `3.0.0-beta.1` and installed again?

**Comment by hottehead** [comment]
Yes, I did. I do have the up to date code of cache plugin in node_modules.

**Comment by jpodwys** [comment]
Thank you for the report and your patience--I was on vacation Monday and Tuesday. I hope to work on this by the end of the week.

**Comment by jpodwys** [comment]
@hottehead I apologize, I've been swamped at work this week. I haven't forgotten about this!

**Comment by jpodwys** [comment]
I've been unable to reproduce this issue. I wrote up the following unit tests to try the scenario out and both tests pass. Can you please put together a code sample that reproduces the issue?

```js
const superagentCache = superagentCacheModule(cache, { expiration: 20 });
const app = express();
app.get('/one', (req, res) => {
  res.send(200, { key: 'one' });
});
app.listen(3000);

describe('request: cache-control', () => {

  beforeEach(() => {
    cache.flush();
  });

  it('empty value', (done) => {
    superagent
      .get('localhost:3000/one')
      .use(superagentCache)
      .end((err, response, key) => {
        cache.get(key, (val) => {
          expect(!!val).toBe(true);
          done();
        });
      }
    );
  });
  
  it('no-cache', (done) => {
    superagent
      .get('localhost:3000/one')
      .set({ 'Cache-Control': 'no-cache' })
      .use(superagentCache)
      .end((err, response, key) => {
        cache.get(key, (val) => {
          expect(!!val).toBe(false);
          done();
        });
      }
    );
  });

});
```
