### ISSUE TITLE
Can it be used with React?

### ISSUE THREAD

**Issue by rwb196884** [jpodwys/superagent-cache-plugin#18]
This is what I've got
```
import { Omit } from '@reach/router';
import * as request from 'superagent';
import { SuperAgentRequest } from 'superagent';
import { superagentCache } from 'superagent-cache-plugin'; // Tried adding this.

const requestTimeout = 60 * 1000; // 60 seconds

export const from = ({ apiBaseUrl, endpointUrl, method }: { apiBaseUrl: string; endpointUrl: string; method: HttpMethod }): SuperAgentRequest => {
  return request[method](`${apiBaseUrl}/${endpointUrl}`).timeout(requestTimeout);
};

export const fetchJson = <T>(req: SuperAgentRequest): ApiRequest<T> =>
  req
    .use(superagentCache) // Tried adding this
    .set('Accept', 'application/json')
    .set('Cache-Control', 'no-cache')
    .set('Pragma', 'no-cache');
```

But it doesn't work.
```
src/api.ts:4:33 - error TS7016: Could not find a declaration file for module 'superagent-cache-plugin'. 'C:/Work/Azure/TruthPortalApp/client/node_modules/superagent-cache-plugin/index.js' implicitly has an 'any' type.
```

The documentation says to do `require` but that doesn't seem to work either.

Any ideas?

**Comment by jpodwys** [comment]
I'm not sure why you're seeing that error. Silly question, I know, but have you installed the dependency? In any case, here's a [working codesandbox](https://codesandbox.io/s/kind-darwin-sz9fgd?file=/src/App.js) using import syntax for react, superagent, and superagent-cache-plugin.

**Comment by rwb196884** [comment]
OK, so I actually need two packages:
```
    "superagent-cache-plugin": "3.0.0-beta.1",
    "cache-service-cache-module": "2.0.1"
```
but even so the build fails with
```
import cacheModule from "cache-service-cache-module";
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/api.ts:7:25 - error TS7016: Could not find a declaration file for module 'superagent-cache-plugin'. 'C:/Work/.../client/node_modules/superagent-cache-plugin/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/superagent-cache-plugin` if it exists or add a new declaration (.d.ts) file containing `declare module 'superagent-cache-plugin';`

7 import cachePlugin from "superagent-cache-plugin";
```

**Comment by rwb196884** [comment]
This seems to be a workaround
```
/* eslint-disable @typescript-eslint/no-var-requires */
const cacheModule = require("cache-service-cache-module");
const cachePlugin = require("superagent-cache-plugin");
```

**Comment by rwb196884** [comment]
No it isn't.
> `Uncaught ReferenceError: require is not defined`

**Comment by rwb196884** [comment]
Adding `"vite-plugin-require"` to `devDependencies` doens't fix it.

**Comment by jpodwys** [comment]
> error TS7016: Could not find a declaration file for module 'superagent-cache-plugin'

Based on [this SO answer](https://stackoverflow.com/questions/41462729/typescript-react-could-not-find-a-declaration-file-for-module-react-material), it looks like this may be happening because superagent-cache-plugin and cache-service-cache-module have no type definitions. These packages predate wide adoption of TypeScript. It looks like you have three options
1. Update your codebase to allow imports of modules without type definitions
2. Locally add an empty module type definition
3. Submit a PR with a type definition

Here's another [SO answer detailing how to do options 1 and 2](https://stackoverflow.com/questions/37000981/how-to-import-node-module-in-typescript-without-type-definitions).

**Comment by rwb196884** [comment]
It doesn't work.
And it hasn't been updated for four years so I guess it's defunct.
Shouldn't have used `superagent`.
