### ISSUE TITLE
Not compatible with the superagent 2.x

### ISSUE THREAD

**Issue by keithws** [jpodwys/superagent-cache-plugin#3]
As self-documented in the README.md.

Now that superagent is on to 3.x, any plans to support the latest superagent?

**Comment by jpodwys** [comment]
Yes, I would like to do so.

Can you please explain what incompatibility you've encountered? Are you simply referring to where the docs say it's currently tested against superagent 1.x, or did you encounter an incompatibility when trying to use it with superagent 2.x or 3.x?

**Comment by keithws** [comment]
I had trouble using it with native Promises.

Turns out, I need proxy support on the server side, so I switched to request.

**Comment by jpodwys** [comment]
Haha sounds good. Happy coding!

**Comment by rahulravindran2709** [comment]
Hi,
I have encountered the following issue while trying to use cache plugin with superagent 3.5.2
"Cannot read property 'then' of undefined"

`const superagentDefaults = require('superagent-defaults');
var superagentPromisePlugin = require('superagent-promise-plugin');
superagentPromisePlugin.Promise = require('es6-promise');
var cacheModule = require('cache-service-cache-module');
var cache = new cacheModule({storage: 'session', defaultExpiration: 60});
var superagentCache = require('superagent-cache-plugin')(cache);
var superagent = superagentDefaults();
superagent.use(superagentPromisePlugin);
superagent.use(superagentCache);
superagent.get('url')
.then((response)=>{
//do something
})`

Please correct me if I am doing something wrong here.
Thanks!

**Comment by jpodwys** [comment]
@rahulravindran2709 it looks like you're using three plugins together:

* superagent-defaults,
* superagent-promise-plugin,
* superagent-cache-plugin

A few thoughts: 

1. Plugins can sometimes conflict with one another. Have you confirmed that your code works as expected while using everything in your code snippet except for `superagent-cache-plugin`?
2. I don't understand why you're using `superagent-promise-plugin` when superagent >= 2.x natively supports promises. I know there's a bug related to promises in my code, but I don't believe it would cause the error you're seeing.
3. I've only done minor testing against superagent >= 2.x.

Any additional info you're able to provide would be very helpful.

**Comment by rahulravindran2709** [comment]
@jpodwys 
Hi,

I created a git repo with the error reproducible with that code.
https://github.com/rahulravindran2709/superagent-cache-example

I have removed all other plugins. Please highlight if there is anything wrong with my usage

**Comment by jpodwys** [comment]
Thank you, that was helpful. I've just added a branch to this repo called `next`. I tested it against your example repo and it appears to fix the issue. If you can confirm, then I'll cut a `2.0.0` release of this repo for you to use. The `2.0.0` release should also be compatible with superagent `2.x` and `3.x`.

**Comment by rahulravindran2709** [comment]
Awesome 👍 . The updated build worked for me.
Thanks a lot for your support!

**Comment by jpodwys** [comment]
I've put together a PR ( #4 ) that includes some other changes I wanted to wrap into a `2.0.0` release. I'm going to let it simmer while I think it over and get a code review. If you'd like to review it, I would appreciate that. In the mean time, I'll keep the `next` branch around for you to use until I cut the `2.0.0` release.

**Comment by jpodwys** [comment]
@rahulravindran2709 I've just published the `2.0.0` release to NPM.

**Comment by rahulravindran2709** [comment]
@jpodwys . Thanks for your help! I have started consuming the new version 2.0.0.
