### ISSUE TITLE
add method to empty the cache

### ISSUE THREAD

**Issue by mbsimonovic** [jpodwys/superagent-cache-plugin#8]
i'm working with some read-only data, that rarely changes, so i use a very big expiration value, but once it does then I'd like to just empty the cache. 

Guess a workaround would be a two expiretion() calls?

```
superagentCache.expiration(1); //then wait a second
setTimeout(() => {superagentCache.expiration(24*3600*365)}, 1);
```

hm, on a second thought probably not, but I can always create a new instance.

**Comment by jpodwys** [comment]
[`superagentCache.cache.flush()`](https://github.com/jpodwys/superagent-cache-plugin#superagentcachecache) should do the trick.

**Comment by mbsimonovic** [comment]
um, where do i find that?

**Comment by mbsimonovic** [comment]
ah, i see, it's on https://github.com/jpodwys/cache-service-cache-module#flushcb

**Comment by jpodwys** [comment]
Yeah, `superagentCache.cache` is just whatever cache instance you passed to `superagent-cache-plugin`'s constructor.
